# Generated by Django 4.2.3 on 2023-07-25 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
