# Generated by Django 4.2.3 on 2023-07-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0002_alter_post_edited'),
        ('core_post', '0002_alter_post_table'),
    ]

    operations = [
    ]
