# Generated by Django 4.2.3 on 2023-07-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_user_posts_liked_alter_user_created_and_more'),
        ('core_user', '0005_user_posts_liked'),
    ]

    operations = [
    ]
